### ISSUE TITLE
GLonD3D12: Crash when using with Olive-Editor with RX 580

### ISSUE THREAD

**Issue by Quackdoc** [pal1000/mesa-dist-win#116]
Trying to use GLonD3D12 to get around some AMD opengl driver bugs. sadly both zink and D3D12 drivers are neither working. This is the back trace while using GLonD3D12. 

I did manager to get a BT from zink once or twice, but gdb on windows often kinds of poops itself when using zink and gets very slow and unusable. 

LLVMpipe works fine

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffdba187bfe in stw_unbind_context () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
(gdb) bt
#0  0x00007ffdba187bfe in stw_unbind_context () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
#1  0x00007ffdb9c03c93 in ?? () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
#2  0x00007ffdb9c039c6 in ?? () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
#3  0x00007ffdb9d58218 in stw_unbind_context () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
#4  0x00007ffdb9d56f4c in stw_unbind_context () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
#5  0x00007ffdb9c0b1e2 in stw_make_current () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
#6  0x00007ffdb9c0b490 in stw_make_current () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
#7  0x00007ffdb9c0a858 in libgallium_wgl!DrvSetContext () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\libgallium_wgl.dll
#8  0x00007ffdf90a114c in wglMakeCurrent () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\opengl32.dll
#9  0x00007ffdb8ae9099 in ?? () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\platforms\qwindows.dll
#10 0x00007ffdb8ae627a in ?? () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\platforms\qwindows.dll
#11 0x00007ffdb8aacfb8 in ?? () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\platforms\qwindows.dll
#12 0x00007ffdbd7ca5b0 in Qt5Gui!?create@QOpenGLContext@@QEAA_NXZ () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\Qt5Gui.dll
#13 0x00007ffdbd790384 in Qt5Gui!?init@QGuiApplicationPrivate@@QEAAXXZ () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\Qt5Gui.dll
#14 0x00007ffdbdda105f in Qt5Widgets!?init@QApplicationPrivate@@QEAAXXZ () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\Qt5Widgets.dll
#15 0x00007ffdbdd9d23b in Qt5Widgets!??0QApplication@@QEAA@AEAHPEAPEADH@Z () from C:\Users\Quack\Downloads\Olive-783d9af8-Windows-x86_64-Portable\olive-editor\Qt5Widgets.dll
#16 0x00007ff672a7256d in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

upstream issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7451

**Comment by Quackdoc** [comment]
forgot to upload this, this is the bt from using debug mesa 
[d3d12.txt](https://github.com/pal1000/mesa-dist-win/files/9740779/d3d12.txt)

**Comment by Quackdoc** [comment]
forgot to upload these, 

MINGW debug backtrace file 
[d3d12-mingw.txt](https://github.com/pal1000/mesa-dist-win/files/9740785/d3d12-mingw.txt)

**Comment by pal1000** [comment]
Send the issue report [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues) too.

**Comment by Quackdoc** [comment]
Roger, I just didn't know if it was appropriate to send it there too. for future reference is it safe to assume any mesa issue that are to do with mesa itself and not say the build, be cross reported or just reported upstream?

**Comment by pal1000** [comment]
> For future reference is it safe to assume any mesa issue that are to do with mesa itself and not say the build, be cross reported or just reported upstream?

Reporting only upstream is enough most times. because reporting here is only relevant if there is a build time workaround.
It's a good idea to try MSVC build too.

**Comment by Matthaiks** [comment]
Zink on AMD has been broken since Mesa 22.1.0. https://github.com/pal1000/mesa-dist-win/issues/95

**Comment by Quackdoc** [comment]
GLonD3D12 now works with olive so ill close this, zink still crashes but ill follow #95 for that
