### ISSUE TITLE
mingw startup crash since 23.1.3

### ISSUE THREAD

**Issue by Optiligence** [pal1000/mesa-dist-win#156]
Server 2012 R2: 0xc000007b 
Server 2019: 0xc0000135
Server 2016 apparently exhibits both

23.1.4 and 23.1.5 don’t work as well

also here https://ci.appveyor.com/project/knossos/knossos/builds/47779695

**Comment by pal1000** [comment]
Try setting `GALLIUM_DRIVER=llvmpipe` and `GALLIUM_DRIVER=d3d12` respectively. This should rule out which driver is crashing.  `GALLIUM_DRIVER=d3d12` cannot work on Server 2012 R2 and even 2016 may be too old.

**Comment by Optiligence** [comment]
both don’t work https://ci.appveyor.com/project/knossos/knossos/builds/47820989

**Comment by pal1000** [comment]
Please report [upstream](https://gitlab.freedesktop.org/mesa/mesa/-/issues). Make sure you refer [@xantares](https://gitlab.freedesktop.org/xantares) and [@lygstate](https://gitlab.freedesktop.org/lygstate).

**Comment by rdp** [comment]
For followers, when I attempt to use mingw build with minecraft I get 

```
java.lang.UnsatisfiedLinkError: Failed to locate library: opengl32.dll
	at org.lwjgl.system.Library.loadNative(Library.java:346)
	at org.lwjgl.system.Library.loadNative(Library.java:236)
	at org.lwjgl.system.Library.loadNative(Library.java:217)
	at org.lwjgl.system.Library.loadNative(Library.java:431)
	at org.lwjgl.system.Library.loadNative(Library.java:402)
	at org.lwjgl.opengl.GL.create(GL.java:107)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:85)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)
	at net.minecraft.client.main.Main.main(SourceFile:223)
```

When I use it with https://www.winteracter.com/demo.htm it says "The code execution cannot proceed because zlib.dll was not found. Reinstalling the program may fix this problem." and same for libzstd.dll, though copying those in didn't seem to fix it entirely somehow?  Should I report this upstream?  Unfortunately for msvc builds I get #164 so workaround for now is to use older release (at least 20.1.8 here works https://fdossena.com/?p=mesa/index.frag , though oddly the "text" demo doesn't seem to work with it for some reason, but the rest does so I'm happy ).  Cheers!

**Comment by pal1000** [comment]
Finally I had time to discover the root cause of this. It appears that static linking LLVM with gcc ld results in corrupt binaries.  Workaround: build without llvm if static linking when using gcc.

**Comment by Optiligence** [comment]
[24.1.5](https://ci.appveyor.com/project/knossos/knossos/builds/51608957/) seems to have worked already
