### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by Lolothepro** [pal1000/mesa-dist-win#89]
log:
```
	at drp.b(SourceFile:218) ~[minecraft-1.18.1-client.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at drp.<init>(SourceFile:92) ~[minecraft-1.18.1-client.jar:?]
	at eqa.a(SourceFile:21) ~[minecraft-1.18.1-client.jar:?]
	at dxo.<init>(SourceFile:476) ~[minecraft-1.18.1-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:199) [minecraft-1.18.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:215) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:250) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:148) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:39) [NewLaunch.jar:?]
```

Java crash:

![image](https://user-images.githubusercontent.com/68275908/155030634-3a90b2d1-a926-44ee-90ee-4ab06965d92c.png)

**Comment by pal1000** [comment]
Did you experience crash with MinGW, MSVC or both packages?

**Comment by Lolothepro** [comment]
both packages

**Comment by pal1000** [comment]
What launcher are you using? Windows store one or legacy (Windows 7/8) one?

**Comment by Lolothepro** [comment]
MultiMC

**Comment by pal1000** [comment]
I couldn't reproduce it at my end but it's possible that Mesa3D uses different drivers on your system. What's your CPU and GPU?
If GPU has Vulkan and D3D12 support then default drivers used by Mesa3D are different than my system.

**Comment by Lolothepro** [comment]
GPU: 8800 GT
CPU: XEON X5450

**Comment by pal1000** [comment]
Your [CPU](https://ark.intel.com/content/www/us/en/ark/products/34446/intel-xeon-processor-x5450-12m-cache-3-00-ghz-1333-mhz-fsb.html)) and [GPU](https://www.techpowerup.com/gpu-specs/geforce-8800-gt.c201) architecture is from 2007 which is really old and thus seriously limits what Mesa3D drivers you can use.

You may or may not meet the [minimum requirements for MinGW package](https://github.com/pal1000/mesa-dist-win#differences-between-msvc-and-mingw-packages) (see first entry in enumeration). Too bad Intel Ark webpage for your CPU lacks SIMD instructions information, however this can still be researched with 3rd-party system information tools. On same note, you are clearly affected by [this issue](https://github.com/pal1000/mesa-dist-win#known-issues) as well:
> 64-bit binaries in both MSVC and MinGW packages require a CPU with AVX even though they shouldn't.

### What can you try
Choose one of the following workarounds
- Use MultiMC with latest 32-bit JRE 8 and Mesa3D MSVC package;
- Use MultiMC with Mesa3D MSVC package v22.0.0-rc1 while staying on JDK 17;
- Same as the 2 above but with MinGW package betting your CPU meets the requirements.

**Comment by pal1000** [comment]
I checked your CPU with a [3rd-party website](https://www.cpu-upgrade.com/CPUs/Intel/Xeon/X5450.html)  and you should be OK with MinGW package. It looks that AVX leak caused by swr driver is what triggers the crash,
